// File generated by FlutterFire CLI. 
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGZWflGd8_CVUx8Ht51sT0HF1sl2jn5S8',
    appId: '1:629134095105:web:94b5db5cb3915da4812100',
    messagingSenderId: '629134095105',
    projectId: 'ogrencimnerede',
    authDomain: 'ogrencimnerede.firebaseapp.com',
    storageBucket: 'ogrencimnerede.firebasestorage.app',
    measurementId: 'G-S14T3VNRJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXY2pF5ZBsyuUZSJsqaj3xkok8424uhLo',
    appId: '1:629134095105:android:031f770bbfa4dc50812100',
    messagingSenderId: '629134095105',
    projectId: 'ogrencimnerede',
    storageBucket: 'ogrencimnerede.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZLodc1LAfwAonDYdK6WqOvmu3Qjl97nY',
    appId: '1:629134095105:ios:aea3f211ab9f0623812100',
    messagingSenderId: '629134095105',
    projectId: 'ogrencimnerede',
    storageBucket: 'ogrencimnerede.firebasestorage.app',
    iosBundleId: 'com.example.ogrencimNerede',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZLodc1LAfwAonDYdK6WqOvmu3Qjl97nY',
    appId: '1:629134095105:ios:aea3f211ab9f0623812100',
    messagingSenderId: '629134095105',
    projectId: 'ogrencimnerede',
    storageBucket: 'ogrencimnerede.firebasestorage.app',
    iosBundleId: 'com.example.ogrencimNerede',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGZWflGd8_CVUx8Ht51sT0HF1sl2jn5S8',
    appId: '1:629134095105:web:f41306d76a1f5430812100',
    messagingSenderId: '629134095105',
    projectId: 'ogrencimnerede',
    authDomain: 'ogrencimnerede.firebaseapp.com',
    storageBucket: 'ogrencimnerede.firebasestorage.app',
    measurementId: 'G-RH8JY16KM4',
  );
}
