platform :ios, '14.0'

use_frameworks!
use_modular_headers!

flutter_application_path = ENV['FLUTTER_APPLICATION_PATH'] || '../'
eval(File.read(File.join(flutter_application_path, 'packages', 'flutter_tools', 'bin', 'podhelper.rb')), binding)

target 'Runner' do
  install_all_flutter_pods(flutter_application_path)
end
