ENV['COCOAPODS_DISABLE_STATS'] = 'true'
ENV['COCOAPODS_NO_REPOS_UPDATE'] = 'true'
ENV['CP_REPO_UPDATE'] = 'false'
platform :ios, '14.0'

use_frameworks!
use_modular_headers!

flutter_application_path = File.expand_path('..', __dir__)
podhelper = File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

unless File.exist?(podhelper)
  puts "⚙️ podhelper.rb bulunamadı, Flutter modülleri hazırlanıyor..."
  system("flutter precache")
  system("flutter build ios --no-codesign")
end

load podhelper

target 'Runner' do
  install_all_flutter_pods(flutter_application_path)
end
